// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAz53g6FvGyQEXaaBVlpCMJ9Hr2QfMvXMU',
    appId: '1:541840919230:web:d03dc9701f1dbf16092cef',
    messagingSenderId: '541840919230',
    projectId: 'agricart-53501',
    authDomain: 'agricart-53501.firebaseapp.com',
    storageBucket: 'agricart-53501.appspot.com',
    databaseURL: 'https://agricart-53501-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABE4VNQ7JDXQGycTXNz_djoMHSD42KG0I',
    appId: '1:541840919230:android:cc6ee71eb756c470092cef',
    messagingSenderId: '541840919230',
    projectId: 'agricart-53501',
    storageBucket: 'agricart-53501.firebasestorage.app',
    databaseURL: 'https://agricart-53501-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABE4VNQ7JDXQGycTXNz_djoMHSD42KG0I',
    appId: '1:541840919230:ios:cc6ee71eb756c470092cef',
    messagingSenderId: '541840919230',
    projectId: 'agricart-53501',
    storageBucket: 'agricart-53501.firebasestorage.app',
    databaseURL: 'https://agricart-53501-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABE4VNQ7JDXQGycTXNz_djoMHSD42KG0I',
    appId: '1:541840919230:ios:cc6ee71eb756c470092cef',
    messagingSenderId: '541840919230',
    projectId: 'agricart-53501',
    storageBucket: 'agricart-53501.firebasestorage.app',
    databaseURL: 'https://agricart-53501-default-rtdb.firebaseio.com',
  );
}

