-- Create delivery_fees table with columns for each barangay
-- Each barangay column stores the delivery fee amount as DECIMAL(10,2)

CREATE TABLE IF NOT EXISTS delivery_fees (
    id SERIAL PRIMARY KEY,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    -- Barangay columns (sanitized names for valid SQL identifiers)
    airport DECIMAL(10,2) DEFAULT 0,
    alta_vista DECIMAL(10,2) DEFAULT 0,
    bagong_also_bagongbong DECIMAL(10,2) DEFAULT 0,
    bagong_buhay DECIMAL(10,2) DEFAULT 0,
    bantigue DECIMAL(10,2) DEFAULT 0,
    barangay_1_poblacion_south DECIMAL(10,2) DEFAULT 0,
    barangay_2_poblacion_south DECIMAL(10,2) DEFAULT 0,
    barangay_3_poblacion_south DECIMAL(10,2) DEFAULT 0,
    barangay_4_poblacion_south DECIMAL(10,2) DEFAULT 0,
    barangay_5_poblacion_south DECIMAL(10,2) DEFAULT 0,
    barangay_6_poblacion_south DECIMAL(10,2) DEFAULT 0,
    barangay_7_poblacion_south DECIMAL(10,2) DEFAULT 0,
    barangay_8_poblacion_south DECIMAL(10,2) DEFAULT 0,
    barangay_9_poblacion_south DECIMAL(10,2) DEFAULT 0,
    barangay_10_poblacion_south DECIMAL(10,2) DEFAULT 0,
    barangay_11_poblacion_north DECIMAL(10,2) DEFAULT 0,
    barangay_12_poblacion_north DECIMAL(10,2) DEFAULT 0,
    barangay_13_poblacion_north DECIMAL(10,2) DEFAULT 0,
    barangay_14_poblacion_north DECIMAL(10,2) DEFAULT 0,
    barangay_15_poblacion_north DECIMAL(10,2) DEFAULT 0,
    barangay_16_poblacion_north DECIMAL(10,2) DEFAULT 0,
    barangay_17_poblacion_north DECIMAL(10,2) DEFAULT 0,
    barangay_18_poblacion_north DECIMAL(10,2) DEFAULT 0,
    barangay_19_poblacion_north DECIMAL(10,2) DEFAULT 0,
    barangay_20_poblacion_north DECIMAL(10,2) DEFAULT 0,
    barangay_21_poblacion_east DECIMAL(10,2) DEFAULT 0,
    barangay_22_poblacion_east DECIMAL(10,2) DEFAULT 0,
    barangay_23_poblacion_east DECIMAL(10,2) DEFAULT 0,
    barangay_24_poblacion_east DECIMAL(10,2) DEFAULT 0,
    barangay_25_poblacion_east DECIMAL(10,2) DEFAULT 0,
    barangay_26_poblacion_west DECIMAL(10,2) DEFAULT 0,
    barangay_27_poblacion_west DECIMAL(10,2) DEFAULT 0,
    barangay_28_poblacion_west DECIMAL(10,2) DEFAULT 0,
    barangay_29_poblacion_west DECIMAL(10,2) DEFAULT 0,
    batuan DECIMAL(10,2) DEFAULT 0,
    bayog DECIMAL(10,2) DEFAULT 0,
    biliboy DECIMAL(10,2) DEFAULT 0,
    borok DECIMAL(10,2) DEFAULT 0,
    cabaon_an DECIMAL(10,2) DEFAULT 0,
    cabulihan DECIMAL(10,2) DEFAULT 0,
    cabintan DECIMAL(10,2) DEFAULT 0,
    cagbuhangin DECIMAL(10,2) DEFAULT 0,
    camp_downes DECIMAL(10,2) DEFAULT 0,
    can_adieng DECIMAL(10,2) DEFAULT 0,
    can_untog DECIMAL(10,2) DEFAULT 0,
    catmon DECIMAL(10,2) DEFAULT 0,
    cogon_combado DECIMAL(10,2) DEFAULT 0,
    concepcion DECIMAL(10,2) DEFAULT 0,
    curva DECIMAL(10,2) DEFAULT 0,
    danao DECIMAL(10,2) DEFAULT 0,
    danhug DECIMAL(10,2) DEFAULT 0,
    dayhagan DECIMAL(10,2) DEFAULT 0,
    dolores DECIMAL(10,2) DEFAULT 0,
    domonar DECIMAL(10,2) DEFAULT 0,
    don_felipe_larrazabal DECIMAL(10,2) DEFAULT 0,
    don_potenciano_larrazabal DECIMAL(10,2) DEFAULT 0,
    dona_feliza_z_mejia DECIMAL(10,2) DEFAULT 0,
    donghol DECIMAL(10,2) DEFAULT 0,
    esperanza DECIMAL(10,2) DEFAULT 0,
    gaas DECIMAL(10,2) DEFAULT 0,
    green_valley DECIMAL(10,2) DEFAULT 0,
    guintigui_an DECIMAL(10,2) DEFAULT 0,
    hibunawon DECIMAL(10,2) DEFAULT 0,
    hugpa DECIMAL(10,2) DEFAULT 0,
    ipil DECIMAL(10,2) DEFAULT 0,
    juaton DECIMAL(10,2) DEFAULT 0,
    kadaohan DECIMAL(10,2) DEFAULT 0,
    labrador_balion DECIMAL(10,2) DEFAULT 0,
    lao DECIMAL(10,2) DEFAULT 0,
    leondoni DECIMAL(10,2) DEFAULT 0,
    libertad DECIMAL(10,2) DEFAULT 0,
    liberty DECIMAL(10,2) DEFAULT 0,
    licuma DECIMAL(10,2) DEFAULT 0,
    liloan DECIMAL(10,2) DEFAULT 0,
    linao DECIMAL(10,2) DEFAULT 0,
    luna DECIMAL(10,2) DEFAULT 0,
    mabato DECIMAL(10,2) DEFAULT 0,
    mabini DECIMAL(10,2) DEFAULT 0,
    macabug DECIMAL(10,2) DEFAULT 0,
    magaswi DECIMAL(10,2) DEFAULT 0,
    mahayag DECIMAL(10,2) DEFAULT 0,
    mahayahay DECIMAL(10,2) DEFAULT 0,
    manlilinao DECIMAL(10,2) DEFAULT 0,
    margen DECIMAL(10,2) DEFAULT 0,
    mas_in DECIMAL(10,2) DEFAULT 0,
    matica_a DECIMAL(10,2) DEFAULT 0,
    milagro DECIMAL(10,2) DEFAULT 0,
    monterico DECIMAL(10,2) DEFAULT 0,
    nasunogan DECIMAL(10,2) DEFAULT 0,
    naungan DECIMAL(10,2) DEFAULT 0,
    nueva_sociedad DECIMAL(10,2) DEFAULT 0,
    nueva_vista DECIMAL(10,2) DEFAULT 0,
    patag DECIMAL(10,2) DEFAULT 0,
    punta DECIMAL(10,2) DEFAULT 0,
    quezon_jr DECIMAL(10,2) DEFAULT 0,
    rufina_m_tan DECIMAL(10,2) DEFAULT 0,
    sabang_bao DECIMAL(10,2) DEFAULT 0,
    salvacion DECIMAL(10,2) DEFAULT 0,
    san_antonio DECIMAL(10,2) DEFAULT 0,
    san_isidro DECIMAL(10,2) DEFAULT 0,
    san_jose DECIMAL(10,2) DEFAULT 0,
    san_juan DECIMAL(10,2) DEFAULT 0,
    san_pablo_simangan DECIMAL(10,2) DEFAULT 0,
    san_vicente DECIMAL(10,2) DEFAULT 0,
    santo_nino DECIMAL(10,2) DEFAULT 0,
    sumangga DECIMAL(10,2) DEFAULT 0,
    tambulilid DECIMAL(10,2) DEFAULT 0,
    tongonan DECIMAL(10,2) DEFAULT 0,
    valencia DECIMAL(10,2) DEFAULT 0,
    alegria DECIMAL(10,2) DEFAULT 0
);

-- Create index on updated_at for faster queries
CREATE INDEX IF NOT EXISTS idx_delivery_fees_updated_at ON delivery_fees(updated_at);

-- Insert initial row with all fees set to 0
INSERT INTO delivery_fees (id) VALUES (1) ON CONFLICT (id) DO NOTHING;

-- Add comment to table
COMMENT ON TABLE delivery_fees IS 'Stores delivery fees for all Ormoc barangays. Each column represents one barangay. Only one row (id=1) is used to store all fees.';

