class OrmocBarangays {
  static const List<String> barangays = [
    'Airport',
    'Alta Vista',
    'Bagong (also Bagongbong)',
    'Bagong Buhay',
    'Bantigue',
    'Barangay 1 (Poblacion South)',
    'Barangay 2 (Poblacion South)',
    'Barangay 3 (Poblacion South)',
    'Barangay 4 (Poblacion South)',
    'Barangay 5 (Poblacion South)',
    'Barangay 6 (Poblacion South)',
    'Barangay 7 (Poblacion South)',
    'Barangay 8 (Poblacion South)',
    'Barangay 9 (Poblacion South)',
    'Barangay 10 (Poblacion South)',
    'Barangay 11 (Poblacion North)',
    'Barangay 12 (Poblacion North)',
    'Barangay 13 (Poblacion North)',
    'Barangay 14 (Poblacion North)',
    'Barangay 15 (Poblacion North)',
    'Barangay 16 (Poblacion North)',
    'Barangay 17 (Poblacion North)',
    'Barangay 18 (Poblacion North)',
    'Barangay 19 (Poblacion North)',
    'Barangay 20 (Poblacion North)',
    'Barangay 21 (Poblacion East)',
    'Barangay 22 (Poblacion East)',
    'Barangay 23 (Poblacion East)',
    'Barangay 24 (Poblacion East)',
    'Barangay 25 (Poblacion East)',
    'Barangay 26 (Poblacion West)',
    'Barangay 27 (Poblacion West)',
    'Barangay 28 (Poblacion West)',
    'Barangay 29 (Poblacion West)',
    'Batuan',
    'Bayog',
    'Biliboy',
    'Borok',
    'Cabaon-an',
    'Cabulihan',
    'Cabintan',
    'Cagbuhangin',
    'Camp Downes',
    'Can-adieng',
    'Can-untog',
    'Catmon',
    'Cogon Combado',
    'Concepcion',
    'Curva',
    'Danao',
    'Danhug',
    'Dayhagan',
    'Dolores',
    'Domonar',
    'Don Felipe Larrazabal',
    'Don Potenciano Larrazabal',
    'Doña Feliza Z. Mejia',
    'Donghol',
    'Esperanza',
    'Gaas',
    'Green Valley',
    'Guintigui-an',
    'Hibunawon',
    'Hugpa',
    'Ipil',
    'Juaton',
    'Kadaohan',
    'Labrador (Balion)',
    'Lao',
    'Leondoni',
    'Libertad',
    'Liberty',
    'Licuma',
    'Liloan',
    'Linao',
    'Luna',
    'Mabato',
    'Mabini',
    'Macabug',
    'Magaswi',
    'Mahayag',
    'Mahayahay',
    'Manlilinao',
    'Margen',
    'Mas-in',
    'Matica-a',
    'Milagro',
    'Monterico',
    'Nasunogan',
    'Naungan',
    'Nueva Sociedad',
    'Nueva Vista',
    'Patag',
    'Punta',
    'Quezon, Jr.',
    'Rufina M. Tan',
    'Sabang Bao',
    'Salvacion',
    'San Antonio',
    'San Isidro',
    'San Jose',
    'San Juan',
    'San Pablo (Simangan)',
    'San Vicente',
    'Santo Niño',
    'Sumangga',
    'Tambulilid',
    'Tongonan',
    'Valencia',
    'Alegria',
  ];

  // Search functionality for barangays
  static List<String> searchBarangays(String query) {
    if (query.isEmpty) return barangays;
    
    return barangays.where((barangay) => 
      barangay.toLowerCase().contains(query.toLowerCase())
    ).toList();
  }
}
